# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alice/Desktop/learn_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alice/Desktop/learn_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alice/Desktop/learn_opengl/CMakeFiles /home/alice/Desktop/learn_opengl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alice/Desktop/learn_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_window

# Build rule for target.
hello_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_window
.PHONY : hello_window

# fast build rule for target.
hello_window/fast:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/build
.PHONY : hello_window/fast

#=============================================================================
# Target rules for targets named glm_test

# Build rule for target.
glm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_test
.PHONY : glm_test

# fast build rule for target.
glm_test/fast:
	$(MAKE) -f CMakeFiles/glm_test.dir/build.make CMakeFiles/glm_test.dir/build
.PHONY : glm_test/fast

glad/src/glad.o: glad/src/glad.c.o

.PHONY : glad/src/glad.o

# target to build an object file
glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/glad/src/glad.c.o
.PHONY : glad/src/glad.c.o

glad/src/glad.i: glad/src/glad.c.i

.PHONY : glad/src/glad.i

# target to preprocess a source file
glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/glad/src/glad.c.i
.PHONY : glad/src/glad.c.i

glad/src/glad.s: glad/src/glad.c.s

.PHONY : glad/src/glad.s

# target to generate assembly for a file
glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/glad/src/glad.c.s
.PHONY : glad/src/glad.c.s

src/glm_test.o: src/glm_test.cpp.o

.PHONY : src/glm_test.o

# target to build an object file
src/glm_test.cpp.o:
	$(MAKE) -f CMakeFiles/glm_test.dir/build.make CMakeFiles/glm_test.dir/src/glm_test.cpp.o
.PHONY : src/glm_test.cpp.o

src/glm_test.i: src/glm_test.cpp.i

.PHONY : src/glm_test.i

# target to preprocess a source file
src/glm_test.cpp.i:
	$(MAKE) -f CMakeFiles/glm_test.dir/build.make CMakeFiles/glm_test.dir/src/glm_test.cpp.i
.PHONY : src/glm_test.cpp.i

src/glm_test.s: src/glm_test.cpp.s

.PHONY : src/glm_test.s

# target to generate assembly for a file
src/glm_test.cpp.s:
	$(MAKE) -f CMakeFiles/glm_test.dir/build.make CMakeFiles/glm_test.dir/src/glm_test.cpp.s
.PHONY : src/glm_test.cpp.s

src/hello_window.o: src/hello_window.cpp.o

.PHONY : src/hello_window.o

# target to build an object file
src/hello_window.cpp.o:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/src/hello_window.cpp.o
.PHONY : src/hello_window.cpp.o

src/hello_window.i: src/hello_window.cpp.i

.PHONY : src/hello_window.i

# target to preprocess a source file
src/hello_window.cpp.i:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/src/hello_window.cpp.i
.PHONY : src/hello_window.cpp.i

src/hello_window.s: src/hello_window.cpp.s

.PHONY : src/hello_window.s

# target to generate assembly for a file
src/hello_window.cpp.s:
	$(MAKE) -f CMakeFiles/hello_window.dir/build.make CMakeFiles/hello_window.dir/src/hello_window.cpp.s
.PHONY : src/hello_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello_window"
	@echo "... glm_test"
	@echo "... glad/src/glad.o"
	@echo "... glad/src/glad.i"
	@echo "... glad/src/glad.s"
	@echo "... src/glm_test.o"
	@echo "... src/glm_test.i"
	@echo "... src/glm_test.s"
	@echo "... src/hello_window.o"
	@echo "... src/hello_window.i"
	@echo "... src/hello_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

